//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKS
    {
        public int MARKID { get; set; }
        public Nullable<int> STDID { get; set; }
        public Nullable<byte> LECTUREID { get; set; }
        public Nullable<byte> EXAM1 { get; set; }
        public Nullable<byte> EXAM2 { get; set; }
        public Nullable<byte> EXAM3 { get; set; }
        public Nullable<byte> PROJECT { get; set; }
        public Nullable<decimal> AVERAGE { get; set; }
        public Nullable<bool> SITUATION { get; set; }
    
        public virtual LECTURES LECTURES { get; set; }
        public virtual STUDENTS STUDENTS { get; set; }
    }
}
