//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbSchoolEntities : DbContext
    {
        public DbSchoolEntities()
            : base("name=DbSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLUBS> CLUBS { get; set; }
        public virtual DbSet<LECTURES> LECTURES { get; set; }
        public virtual DbSet<MARKS> MARKS { get; set; }
        public virtual DbSet<STUDENTS> STUDENTS { get; set; }
    }
}
