//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENTS()
        {
            this.MARKS = new HashSet<MARKS>();
        }
    
        public int STDID { get; set; }
        public string STDNAME { get; set; }
        public string STDSURNAME { get; set; }
        public string STDGENDER { get; set; }
        public Nullable<byte> STDCLUB { get; set; }
    
        public virtual CLUBS CLUBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKS> MARKS { get; set; }
    }
}
